# Generated by Django 5.2.1 on 2026-02-20 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.service'),
        ),
    ]
