# Generated by Django 5.2.1 on 2026-02-22 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_alter_workerprofile_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='parts_used',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='bills/'),
        ),
        migrations.AddField(
            model_name='bill',
            name='service_type',
            field=models.CharField(default='General Service', max_length=200),
        ),
        migrations.AddField(
            model_name='bill',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
