# Generated by Django 5.2.1 on 2026-02-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_bill_parts_used_bill_pdf_bill_service_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('service_type', models.CharField(choices=[('Electrical', 'Electrical'), ('Plumbing', 'Plumbing')], max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='parts/')),
            ],
        ),
    ]
