# Generated by Django 5.2.1 on 2026-02-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_part'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('subtotal', models.FloatField()),
                ('shipping', models.FloatField()),
                ('tax', models.FloatField()),
                ('grand_total', models.FloatField()),
                ('payment_method', models.CharField(default='Cash on Delivery', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
