# Generated by Django 5.2.1 on 2026-02-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='full_name',
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(default='c', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default='k', max_length=200),
        ),
    ]
