# Generated by Django 5.2.1 on 2026-02-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_alter_order_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='price',
        ),
        migrations.AddField(
            model_name='part',
            name='bulk_min_quantity',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='part',
            name='bulk_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='part',
            name='normal_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='part',
            name='worker_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
