# Generated by Django 5.2.1 on 2026-03-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0011_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
