# Generated by Django 5.2.1 on 2026-03-15 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0012_customuser_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='location',
        ),
    ]
